// Countries available on freebinchecker.com for BIN search
// slug is derived from the country name (lowercase, spaces to hyphens)

export interface BinCountry {
  name: string
  slug: string
  code: string
  flag: string
}

export const BIN_COUNTRIES: BinCountry[] = [
  { name: 'United States', slug: 'united-states', code: 'US', flag: '🇺🇸' },
  { name: 'United Kingdom', slug: 'united-kingdom', code: 'GB', flag: '🇬🇧' },
  { name: 'Canada', slug: 'canada', code: 'CA', flag: '🇨🇦' },
  { name: 'Mexico', slug: 'mexico', code: 'MX', flag: '🇲🇽' },
  { name: 'Brazil', slug: 'brazil', code: 'BR', flag: '🇧🇷' },
  { name: 'Argentina', slug: 'argentina', code: 'AR', flag: '🇦🇷' },
  { name: 'Colombia', slug: 'colombia', code: 'CO', flag: '🇨🇴' },
  { name: 'Chile', slug: 'chile', code: 'CL', flag: '🇨🇱' },
  { name: 'Peru', slug: 'peru', code: 'PE', flag: '🇵🇪' },
  { name: 'Ecuador', slug: 'ecuador', code: 'EC', flag: '🇪🇨' },
  { name: 'Venezuela', slug: 'venezuela', code: 'VE', flag: '🇻🇪' },
  { name: 'Spain', slug: 'spain', code: 'ES', flag: '🇪🇸' },
  { name: 'Germany', slug: 'germany', code: 'DE', flag: '🇩🇪' },
  { name: 'France', slug: 'france', code: 'FR', flag: '🇫🇷' },
  { name: 'Italy', slug: 'italy', code: 'IT', flag: '🇮🇹' },
  { name: 'Portugal', slug: 'portugal', code: 'PT', flag: '🇵🇹' },
  { name: 'Netherlands', slug: 'the-netherlands', code: 'NL', flag: '🇳🇱' },
  { name: 'Belgium', slug: 'belgium', code: 'BE', flag: '🇧🇪' },
  { name: 'Switzerland', slug: 'switzerland', code: 'CH', flag: '🇨🇭' },
  { name: 'Austria', slug: 'austria', code: 'AT', flag: '🇦🇹' },
  { name: 'Sweden', slug: 'sweden', code: 'SE', flag: '🇸🇪' },
  { name: 'Norway', slug: 'norway', code: 'NO', flag: '🇳🇴' },
  { name: 'Denmark', slug: 'denmark', code: 'DK', flag: '🇩🇰' },
  { name: 'Finland', slug: 'finland', code: 'FI', flag: '🇫🇮' },
  { name: 'Ireland', slug: 'ireland', code: 'IE', flag: '🇮🇪' },
  { name: 'Poland', slug: 'poland', code: 'PL', flag: '🇵🇱' },
  { name: 'Czech Republic', slug: 'czech-republic', code: 'CZ', flag: '🇨🇿' },
  { name: 'Romania', slug: 'romania', code: 'RO', flag: '🇷🇴' },
  { name: 'Hungary', slug: 'hungary', code: 'HU', flag: '🇭🇺' },
  { name: 'Greece', slug: 'greece', code: 'GR', flag: '🇬🇷' },
  { name: 'Russia', slug: 'russian-federation', code: 'RU', flag: '🇷🇺' },
  { name: 'Ukraine', slug: 'ukraine', code: 'UA', flag: '🇺🇦' },
  { name: 'Turkey', slug: 'turkey', code: 'TR', flag: '🇹🇷' },
  { name: 'India', slug: 'india', code: 'IN', flag: '🇮🇳' },
  { name: 'China', slug: 'china', code: 'CN', flag: '🇨🇳' },
  { name: 'Japan', slug: 'japan', code: 'JP', flag: '🇯🇵' },
  { name: 'South Korea', slug: 'south-korea', code: 'KR', flag: '🇰🇷' },
  { name: 'Australia', slug: 'australia', code: 'AU', flag: '🇦🇺' },
  { name: 'New Zealand', slug: 'new-zealand', code: 'NZ', flag: '🇳🇿' },
  { name: 'Singapore', slug: 'singapore', code: 'SG', flag: '🇸🇬' },
  { name: 'Hong Kong', slug: 'hong-kong', code: 'HK', flag: '🇭🇰' },
  { name: 'Taiwan', slug: 'taiwan', code: 'TW', flag: '🇹🇼' },
  { name: 'Thailand', slug: 'thailand', code: 'TH', flag: '🇹🇭' },
  { name: 'Philippines', slug: 'philippines', code: 'PH', flag: '🇵🇭' },
  { name: 'Malaysia', slug: 'malaysia', code: 'MY', flag: '🇲🇾' },
  { name: 'Indonesia', slug: 'indonesia', code: 'ID', flag: '🇮🇩' },
  { name: 'Vietnam', slug: 'vietnam', code: 'VN', flag: '🇻🇳' },
  { name: 'Pakistan', slug: 'pakistan', code: 'PK', flag: '🇵🇰' },
  { name: 'Bangladesh', slug: 'bangladesh', code: 'BD', flag: '🇧🇩' },
  { name: 'Saudi Arabia', slug: 'saudi-arabia', code: 'SA', flag: '🇸🇦' },
  { name: 'United Arab Emirates', slug: 'united-arab-emirates', code: 'AE', flag: '🇦🇪' },
  { name: 'Israel', slug: 'israel', code: 'IL', flag: '🇮🇱' },
  { name: 'Kuwait', slug: 'kuwait', code: 'KW', flag: '🇰🇼' },
  { name: 'Qatar', slug: 'qatar', code: 'QA', flag: '🇶🇦' },
  { name: 'South Africa', slug: 'south-africa', code: 'ZA', flag: '🇿🇦' },
  { name: 'Nigeria', slug: 'nigeria', code: 'NG', flag: '🇳🇬' },
  { name: 'Egypt', slug: 'egypt', code: 'EG', flag: '🇪🇬' },
  { name: 'Kenya', slug: 'kenya', code: 'KE', flag: '🇰🇪' },
  { name: 'Morocco', slug: 'morocco', code: 'MA', flag: '🇲🇦' },
  { name: 'Costa Rica', slug: 'costa-rica', code: 'CR', flag: '🇨🇷' },
  { name: 'Panama', slug: 'panama', code: 'PA', flag: '🇵🇦' },
  { name: 'Dominican Republic', slug: 'dominican-republic', code: 'DO', flag: '🇩🇴' },
  { name: 'Cuba', slug: 'cuba', code: 'CU', flag: '🇨🇺' },
  { name: 'Uruguay', slug: 'uruguay', code: 'UY', flag: '🇺🇾' },
  { name: 'Bolivia', slug: 'bolivia', code: 'BO', flag: '🇧🇴' },
  { name: 'Paraguay', slug: 'paraguay', code: 'PY', flag: '🇵🇾' },
  { name: 'Guatemala', slug: 'guatemala', code: 'GT', flag: '🇬🇹' },
  { name: 'Honduras', slug: 'honduras', code: 'HN', flag: '🇭🇳' },
  { name: 'El Salvador', slug: 'el-salvador', code: 'SV', flag: '🇸🇻' },
  { name: 'Nicaragua', slug: 'nicaragua', code: 'NI', flag: '🇳🇮' },
  { name: 'Croatia', slug: 'croatia', code: 'HR', flag: '🇭🇷' },
  { name: 'Bulgaria', slug: 'bulgaria', code: 'BG', flag: '🇧🇬' },
  { name: 'Slovakia', slug: 'slovakia-slovak-republic', code: 'SK', flag: '🇸🇰' },
  { name: 'Lithuania', slug: 'lithuania', code: 'LT', flag: '🇱🇹' },
  { name: 'Latvia', slug: 'latvia', code: 'LV', flag: '🇱🇻' },
  { name: 'Estonia', slug: 'estonia', code: 'EE', flag: '🇪🇪' },
  { name: 'Iceland', slug: 'iceland', code: 'IS', flag: '🇮🇸' },
  { name: 'Luxembourg', slug: 'luxembourg', code: 'LU', flag: '🇱🇺' },
  { name: 'Cyprus', slug: 'cyprus', code: 'CY', flag: '🇨🇾' },
  { name: 'Malta', slug: 'malta', code: 'MT', flag: '🇲🇹' },
  { name: 'Slovenia', slug: 'slovenia', code: 'SI', flag: '🇸🇮' },
  { name: 'Serbia', slug: 'serbia', code: 'RS', flag: '🇷🇸' },
  { name: 'Bosnia and Herzegovina', slug: 'bosnia-and-herzegovina', code: 'BA', flag: '🇧🇦' },
  { name: 'North Macedonia', slug: 'macedonia', code: 'MK', flag: '🇲🇰' },
  { name: 'Albania', slug: 'albania', code: 'AL', flag: '🇦🇱' },
  { name: 'Montenegro', slug: 'montenegro', code: 'ME', flag: '🇲🇪' },
  { name: 'Kosovo', slug: 'kosovo', code: 'XK', flag: '🇽🇰' },
  { name: 'Georgia', slug: 'georgia', code: 'GE', flag: '🇬🇪' },
  { name: 'Armenia', slug: 'armenia', code: 'AM', flag: '🇦🇲' },
  { name: 'Azerbaijan', slug: 'azerbaijan', code: 'AZ', flag: '🇦🇿' },
  { name: 'Kazakhstan', slug: 'kazakhstan', code: 'KZ', flag: '🇰🇿' },
  { name: 'Uzbekistan', slug: 'uzbekistan', code: 'UZ', flag: '🇺🇿' },
  { name: 'Philippines', slug: 'philippines', code: 'PH', flag: '🇵🇭' },
  { name: 'Jordan', slug: 'jordan', code: 'JO', flag: '🇯🇴' },
  { name: 'Lebanon', slug: 'lebanon', code: 'LB', flag: '🇱🇧' },
  { name: 'Iraq', slug: 'iraq', code: 'IQ', flag: '🇮🇶' },
  { name: 'Iran', slug: 'iran', code: 'IR', flag: '🇮🇷' },
]
